# .github/workflows/update_bw_snapshots.yml

name: Update BW Snapshots

on:
  workflow_dispatch:        # manual trigger
  schedule:
    - cron: "0 * * * *"    # every hour at minute 0 UTC

permissions:
  contents: write           # needed to commit snapshot JSON back to repo

jobs:
  update-bw-snapshots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update BW snapshots
        run: python -m scripts.fetch.update_bw_snapshots
        # -m allows running as a module with package imports

      - name: Commit and push updated snapshots
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add docs/data/bw_snapshots.json
          git commit -m "Update BW snapshots" || echo "No changes to commit"
          git push
