name: Merge BW + KDH AIS Data

on:
  workflow_dispatch:        # manual trigger
  schedule:
    - cron: "*/15 * * * *"    # every 15 minutes

permissions:
  contents: write           # required to commit JSON back to repo

jobs:
  merge-ais:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run BW + KDH merge
        run: python -m scripts.fetch.merge_bw_kdh

      - name: Commit and push merged AIS
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add docs/data/ais_msg_main2.json
          git commit -m "Update merged AIS data" || echo "No changes to commit"
          git push
